export * from './CertainMoviesList';
export * from './Footer';
export * from './GenresContainer';
export * from './Header';
export * from './MovieInfo';
export * from './MoviesListCard';
export * from './PosterPrewiew';
export * from './Search';
export * from './StarsRating';
